# coding: utf-8

#
#  Copyright Douglas Williams, 2018
#  All Rights Reserved
#


# Thresholds used by Trend Plots
THRESH_FETAL_BRADYCARDIA = 110
THRESH_FETAL_TACHYCARDIA = 160

THRESH_ADULT_BRADYCARDIA = 60
THRESH_ADULT_TACHYCARDIA = 100

THRESH_LOW_VARIABILITY = 5.5
THRESH_HIGH_VARIABILITY = 25.5
THRESH_TACHYSYSTOLE = 5.5
